version: '3.3'
services:
  compositions:
    container_name: compositions
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /system/appdata/compositeurs:/app
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8000:8000'
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
