services:
  compositions:
    container_name: compositions
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /system/appdata/compositions/:/app
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8000:8000'
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
