# Generated by Django 4.2.11 on 2024-08-07 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_date_creation_alter_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='end_publication',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='start_publication',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
