# Generated by Django 4.2.11 on 2024-08-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_morceau_news_morceau'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='order',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
