# Generated by Django 4.2.11 on 2024-08-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('', ''), ('New music', 'New music'), ('Information', 'Information'), ('Concert', 'Concert')], max_length=50),
        ),
    ]
