# Generated by Django 4.2.11 on 2024-03-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morceau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('duree', models.CharField(max_length=5)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('commentaire', models.TextField()),
                ('termine', models.BooleanField()),
                ('mixe', models.BooleanField()),
                ('documentation', models.BooleanField()),
                ('fichier_documentation', models.CharField(max_length=255)),
                ('support', models.CharField(max_length=20)),
                ('liste_instruments', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
