# Generated by Django 4.2.11 on 2024-11-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Name')),
                ('repertoire', models.CharField(blank=True, max_length=250, null=True, verbose_name='Directory')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Style')),
            ],
        ),
        migrations.CreateModel(
            name='Morceau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du morceau')),
                ('duree', models.CharField(blank=True, max_length=8, null=True, verbose_name='Durée du morceau')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('mixed', models.BooleanField(default=False)),
                ('documentation', models.BooleanField(default=False)),
                ('fichier_documentation', models.CharField(blank=True, max_length=255, null=True)),
                ('support', models.CharField(blank=True, max_length=20, null=True)),
                ('download', models.BooleanField(default=True)),
                ('player', models.BooleanField(default=True)),
                ('music_file', models.FileField(blank=True, null=True, upload_to='musics')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='images')),
                ('instrument', models.ManyToManyField(blank=True, to='morceaux.instrument')),
                ('style', models.ManyToManyField(blank=True, to='morceaux.style')),
            ],
        ),
    ]
