# Generated by Django 4.2.11 on 2024-03-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceau',
            name='mixe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='termine',
            field=models.BooleanField(default=False),
        ),
    ]
