# Generated by Django 4.2.11 on 2024-11-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceau',
            name='instrument',
            field=models.ManyToManyField(to='morceaux.instrument'),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='style',
            field=models.ManyToManyField(to='morceaux.style'),
        ),
    ]
