# Generated by Django 4.2.11 on 2024-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0002_alter_morceau_mixe_alter_morceau_termine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceau',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='duree',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Durée du morceau'),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='fichier_documentation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='liste_instruments',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom du morceau'),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='support',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
