# Generated by Django 4.2.11 on 2024-03-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0003_alter_morceau_commentaire_alter_morceau_duree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceau',
            name='commentaire',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='duree',
            field=models.CharField(default='', max_length=5, verbose_name='Durée du morceau'),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='fichier_documentation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='liste_instruments',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='support',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
