# Generated by Django 4.2.11 on 2024-11-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0004_remove_morceau_instrument_remove_morceau_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morceau',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='morceau',
            name='style',
        ),
        migrations.AddField(
            model_name='morceau',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morceaux.instrument'),
        ),
        migrations.AddField(
            model_name='morceau',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morceaux.style'),
        ),
    ]
