# Generated by Django 4.2.11 on 2024-03-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0004_alter_morceau_commentaire_alter_morceau_duree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceau',
            name='commentaire',
            field=models.TextField(default='test'),
        ),
    ]
