# Generated by Django 4.2.11 on 2024-03-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0005_alter_morceau_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'instrument")),
            ],
        ),
        migrations.AlterField(
            model_name='morceau',
            name='commentaire',
            field=models.TextField(default=''),
        ),
    ]
