# Generated by Django 4.2.11 on 2024-03-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0006_instrument_alter_morceau_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceau',
            name='liste_instruments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morceaux.instrument'),
        ),
    ]
