# Generated by Django 4.2.11 on 2024-12-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0007_alter_morceau_image_file_alter_morceau_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceau',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
