# Generated by Django 4.2.11 on 2024-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0010_instrument_repertoire_alter_instrument_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceau',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
