# Generated by Django 4.2.11 on 2024-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0012_morceau_work_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceau',
            name='duree',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Durée du morceau'),
        ),
    ]
