# Generated by Django 4.2.11 on 2024-07-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0013_alter_morceau_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceau',
            name='download',
            field=models.BooleanField(default=True),
        ),
    ]
