# Generated by Django 4.2.11 on 2024-07-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0014_morceau_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceau',
            name='music',
            field=models.FileField(blank=True, upload_to='music'),
        ),
    ]
