# Generated by Django 4.2.11 on 2024-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0015_morceau_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceau',
            name='music',
            field=models.FileField(blank=True, upload_to='music/'),
        ),
    ]
