# Generated by Django 4.2.11 on 2024-07-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0016_alter_morceau_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceau',
            name='music_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='music',
            field=models.FileField(blank=True, upload_to='static/musics/'),
        ),
    ]
