# Generated by Django 4.2.11 on 2024-07-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0017_morceau_music_file_name_alter_morceau_music'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morceau',
            old_name='music',
            new_name='music_file',
        ),
        migrations.RemoveField(
            model_name='morceau',
            name='music_file_name',
        ),
    ]
