# Generated by Django 4.2.11 on 2024-07-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0020_morceau_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Genre')),
            ],
        ),
        migrations.DeleteModel(
            name='Style',
        ),
        migrations.AddField(
            model_name='morceau',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morceaux.genre'),
        ),
    ]
