# Generated by Django 4.2.11 on 2024-07-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0021_genre_delete_style_morceau_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Style',
        ),
        migrations.RenameField(
            model_name='morceau',
            old_name='genre',
            new_name='style',
        ),
    ]
