# Generated by Django 4.2.11 on 2024-07-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0022_rename_genre_style_rename_genre_morceau_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morceau',
            old_name='liste_instruments',
            new_name='instrument',
        ),
    ]
