# Generated by Django 4.2.11 on 2024-07-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0023_rename_liste_instruments_morceau_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceau',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morceaux.instrument'),
        ),
    ]
