# Generated by Django 4.2.11 on 2024-07-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0026_alter_instrument_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morceau',
            name='type',
        ),
        migrations.AlterField(
            model_name='morceau',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morceaux.instrument'),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='Nom du morceau'),
        ),
    ]
