# Generated by Django 4.2.11 on 2024-07-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0027_remove_morceau_type_alter_morceau_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceau',
            name='image_file',
            field=models.FileField(blank=True, upload_to='medias/images/'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='morceau',
            name='music_file',
            field=models.FileField(blank=True, upload_to='medias/musics/'),
        ),
        migrations.AlterField(
            model_name='style',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Style'),
        ),
    ]
