# Generated by Django 4.2.11 on 2024-07-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0028_morceau_image_file_alter_instrument_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morceau',
            name='work_directory',
        ),
    ]
