# Generated by Django 4.2.11 on 2024-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0030_alter_morceau_image_file_alter_morceau_music_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceau',
            name='image_file',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
