# Generated by Django 4.2.11 on 2024-07-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morceaux', '0031_alter_morceau_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morceau',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
