# Generated by Django 4.2.11 on 2024-08-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_config_news_print_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='news_print_sorted_creation_date',
            field=models.BooleanField(default=True),
        ),
    ]
